/** Stable workflow-domain errors shared by the service and HTTP plugin. */

export type WorkflowErrorCode =
  | 'WORKFLOW_NOT_READY'
  | 'WORKFLOW_DRAINING'
  | 'WORKFLOW_NOT_FOUND'
  | 'WORKFLOW_DEFINITION_NOT_FOUND'
  | 'WORKFLOW_DEFINITION_INVALID'
  | 'WORKFLOW_DEFINITION_GRAPH_INVALID'
  | 'WORKFLOW_VERSION_NOT_FOUND'
  | 'WORKFLOW_VERSION_CONFLICT'
  | 'WORKFLOW_VERSION_SOURCE_CONFLICT'
  | 'WORKFLOW_VERSION_SCOPE_CONFLICT'
  | 'WORKFLOW_VERSION_HISTORY_INVALID'
  | 'WORKFLOW_DRAFT_CONFLICT'
  | 'WORKFLOW_GRAPH_INVALID'
  | 'WORKFLOW_HANDLER_NOT_REGISTERED'
  | 'WORKFLOW_ACTIVITY_NOT_REGISTERED'
  | 'WORKFLOW_ACTIVITY_NOT_ALLOWED'
  | 'WORKFLOW_ACTIVITY_INPUT_INVALID'
  | 'WORKFLOW_ACTIVITY_OUTPUT_INVALID'
  | 'WORKFLOW_FANOUT_LIMIT_EXCEEDED'
  | 'WORKFLOW_ATTEMPT_STALE'
  | 'WORKFLOW_MEMORY_KEY_INVALID'
  | 'WORKFLOW_MEMORY_VALUE_INVALID'
  | 'WORKFLOW_MEMORY_LIMIT_EXCEEDED'
  | 'WORKFLOW_MEMORY_CONFLICT'
  | 'WORKFLOW_INTERACTION_NOT_FOUND'
  | 'WORKFLOW_INTERACTION_EXPIRED'
  | 'WORKFLOW_INTERACTION_CLOSED'
  | 'WORKFLOW_INTERACTION_FORBIDDEN'
  | 'WORKFLOW_INTERACTION_INVALID'
  | 'WORKFLOW_INTERACTION_SUBMISSION_CONFLICT'
  | 'WORKFLOW_INTERACTION_SUBMISSION_LIMIT'
  | 'WORKFLOW_INTERACTION_REJECTION_LIMIT'
  | 'WORKFLOW_STATE_INVALID'
  | 'WORKFLOW_INPUT_INVALID'
  | 'WORKFLOW_OUTPUT_INVALID'
  | 'WORKFLOW_EVENT_INVALID'
  | 'WORKFLOW_EVENT_IDEMPOTENCY_INVALID'
  | 'WORKFLOW_EVENT_IDEMPOTENCY_CONFLICT'
  | 'WORKFLOW_START_IDEMPOTENCY_INVALID'
  | 'WORKFLOW_START_IDEMPOTENCY_CONFLICT'
  | 'WORKFLOW_EVENT_QUEUE_FULL'
  | 'WORKFLOW_EVENT_LIMIT_EXCEEDED'
  | 'WORKFLOW_RUNTIME_LIMIT_EXCEEDED'
  | 'WORKFLOW_RUNTIME_OWNED'
  | 'WORKFLOW_RUNTIME_LEASE_LOST'
  | 'WORKFLOW_REQUEST_INVALID'
  | 'WORKFLOW_REQUEST_PARSE_FAILED'
  | 'WORKFLOW_CONFIG_INVALID'
  | 'WORKFLOW_AUTHORITY_REQUIRED'
  | 'WORKFLOW_AUTHORITY_CHANGED'
  | 'WORKFLOW_SCOPE_REQUIRED'
  | 'WORKFLOW_SCOPE_INVALID'
  | 'WORKFLOW_STARTUP_FAILED'
  | 'WORKFLOW_INTERNAL_ERROR';

export class WorkflowError extends Error {
  constructor(
    message: string,
    readonly code: WorkflowErrorCode,
    readonly status: number,
    readonly retryable = false,
  ) {
    super(message);
    this.name = 'WorkflowError';
  }
}

export function workflowNotFound(): WorkflowError {
  return new WorkflowError('Workflow not found', 'WORKFLOW_NOT_FOUND', 404);
}

/** Bound hostile thrown values before they enter durable state or telemetry. */
export function formatWorkflowError(error: unknown): string {
  try {
    const message = error instanceof Error ? error.message : String(error);
    return String(message).slice(0, 2_000);
  } catch {
    return 'Workflow handler failed with an unprintable error';
  }
}
