import { resolve, join, relative, dirname } from 'path';
import { existsSync, mkdirSync, writeFileSync, rmSync, readdirSync } from 'fs';
import { scanRoutes, hasUseClientDirective } from '../router/scanner';
import { buildRouteTree } from '../router/route-tree';
import type { RouteNode } from '../router/types';

// ─── Client Bundle Builder ─────────────────────────────────────────────────

export interface BundleResult {
  /** Absolute path to the output JS file */
  jsPath: string;
  /** URL-safe path for serving (e.g., '/_build/client.js') */
  publicPath: string;
  /** Whether the bundle was rebuilt (false if cached) */
  rebuilt: boolean;
}

/**
 * Build the client-side JS bundle using Bun.build().
 *
 * Entry point: src/frontend/client/hydrate.tsx
 * Outputs to: outDir/client.js
 *
 * The bundle includes:
 * - React + ReactDOM (for hydration)
 * - Client-side router
 * - App provider (sync + auth + state)
 * - All app/ page and layout components (code-split via manifest)
 */
export async function buildClientBundle(
  outDir: string,
  appDir: string = './app'
): Promise<BundleResult> {
  const absOut = resolve(outDir);

  // Clean stale build artifacts before writing new ones.
  // Bun.build with splitting generates chunk-[hash].js files with unique hashes
  // per build. Without cleanup, old chunks accumulate and stale HTML entry points
  // can reference outdated chunks — causing runtime errors like missing tables.
  if (existsSync(absOut)) {
    const entries = readdirSync(absOut);
    for (const entry of entries) {
      // Preserve non-JS assets (e.g., styles.css) that other build steps produce
      if (entry.endsWith('.js') || entry.endsWith('.js.map')) {
        rmSync(join(absOut, entry));
      }
    }
  } else {
    mkdirSync(absOut, { recursive: true });
  }

  // Generate route manifest BEFORE Bun.build so imports are analyzed
  generateRouteManifest(appDir);

  const entrypoint = resolve('src/frontend/client/hydrate.tsx');

  const result = await Bun.build({
    entrypoints: [entrypoint],
    outdir: absOut,
    naming: 'client.[hash].js',
    target: 'browser',
    format: 'esm',
    minify: process.env.NODE_ENV === 'production',
    splitting: true,
    sourcemap: process.env.NODE_ENV === 'production' ? 'none' : 'linked',
    define: {
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'development'),
    },
    external: [],
  });

  if (!result.success) {
    const errors = result.logs.map((l) => l.message).join('\n');
    throw new Error(`Client bundle build failed:\n${errors}`);
  }

  // Find the main entry output
  const mainOutput = result.outputs.find((o) => o.kind === 'entry-point');
  if (!mainOutput) {
    throw new Error('No entry-point output found in bundle result');
  }

  const jsPath = mainOutput.path;
  const fileName = jsPath.split('/').pop()!;
  const publicPath = `/_build/${fileName}`;

  return { jsPath, publicPath, rebuilt: true };
}

// ─── Route Manifest Generation ─────────────────────────────────────────────

const MANIFEST_DIR = resolve('src/frontend/client/_generated');
const MANIFEST_PATH = join(MANIFEST_DIR, 'route-manifest.ts');

/**
 * Generate a route manifest file that maps URL patterns to dynamic imports.
 *
 * The manifest contains static `import()` expressions so Bun.build can
 * analyze them and code-split each route into its own chunk.
 */
function generateRouteManifest(appDir: string): void {
  const files = scanRoutes(appDir);
  const root = buildRouteTree(files);

  // Collect all page entries with their patterns and layout chains
  const entries: Array<{
    pattern: string;
    pageImport: string;
    layoutImports: string[];
    isClient: boolean;
  }> = [];

  collectRouteEntries(root, [], [], entries, resolve(appDir));

  // Ensure _generated directory exists
  if (!existsSync(MANIFEST_DIR)) {
    mkdirSync(MANIFEST_DIR, { recursive: true });
  }

  // Split into client routes (have "use client") and server-only routes
  const clientEntries = entries.filter((e) => e.isClient);
  const serverPatterns = entries.filter((e) => !e.isClient).map((e) => e.pattern);

  // Build the manifest source — only client routes get import() calls
  const lines: string[] = [
    '// AUTO-GENERATED by client-bundle.ts — do not edit',
    '',
    'export interface ManifestEntry {',
    '  pattern: string;',
    '  load: () => Promise<{ default: any }>;',
    '  layouts: Array<() => Promise<{ default: any }>>;',
    '}',
    '',
    '/** Patterns for server-only pages (no JS shipped, no hydration). */',
    `export const serverRoutes: string[] = ${JSON.stringify(serverPatterns)};`,
    '',
    '/** Client pages — these hydrate on the client. */',
    'export const routes: ManifestEntry[] = [',
  ];

  for (const entry of clientEntries) {
    const layoutsStr = entry.layoutImports
      .map((imp) => `    () => import('${imp}'),`)
      .join('\n');

    lines.push('  {');
    lines.push(`    pattern: '${entry.pattern}',`);
    lines.push(`    load: () => import('${entry.pageImport}'),`);
    if (entry.layoutImports.length > 0) {
      lines.push('    layouts: [');
      lines.push(layoutsStr);
      lines.push('    ],');
    } else {
      lines.push('    layouts: [],');
    }
    lines.push('  },');
  }

  lines.push('];');
  lines.push('');

  writeFileSync(MANIFEST_PATH, lines.join('\n'));
}

/**
 * Recursively collect route entries from the tree.
 * For each page, records the pattern and layout chain from root → leaf.
 */
function collectRouteEntries(
  node: RouteNode,
  patternSegments: string[],
  layoutPaths: string[],
  entries: Array<{ pattern: string; pageImport: string; layoutImports: string[]; isClient: boolean }>,
  appDir: string
): void {
  // Accumulate layouts at this level
  const currentLayouts = node.layoutPath
    ? [...layoutPaths, node.layoutPath]
    : layoutPaths;

  // If this node has a page, record it
  if (node.pagePath) {
    const pattern = patternSegments.length > 0
      ? '/' + patternSegments.join('/')
      : '/';

    // Check if this page has "use client" directive
    const isClient = hasUseClientDirective(node.pagePath);

    entries.push({
      pattern,
      pageImport: toManifestImport(node.pagePath),
      layoutImports: currentLayouts.map(toManifestImport),
      isClient,
    });
  }

  // Recurse into children
  for (const child of node.children.values()) {
    collectRouteEntries(
      child,
      [...patternSegments, child.segment],
      currentLayouts,
      entries,
      appDir
    );
  }
}

/**
 * Convert an absolute file path to a `@app/` aliased import.
 * Strips .tsx/.ts extensions (Bun resolves them).
 * Relies on `@app/*` path alias in tsconfig.json mapping to `./app/*`.
 */
function toManifestImport(absolutePath: string): string {
  // Find the /app/ segment and build @app/ alias from there
  const appIdx = absolutePath.lastIndexOf('/app/');
  if (appIdx !== -1) {
    const afterApp = absolutePath.slice(appIdx + 5); // skip "/app/"
    const withoutExt = afterApp.replace(/\.(tsx?|jsx?)$/, '');
    return `@app/${withoutExt}`;
  }
  // Fallback to relative path
  const rel = relative(MANIFEST_DIR, absolutePath);
  const withoutExt = rel.replace(/\.(tsx?|jsx?)$/, '');
  return withoutExt.startsWith('.') ? withoutExt : './' + withoutExt;
}
