/**
 * codes.ts
 *
 * Central registry for Zero observability event codes and formatted prefixes.
 * Platform modules should import these constants instead of inventing ad-hoc
 * strings, keeping logs, warnings, and errors stable across releases.
 */

import type { PlatformCodeDefinition, PlatformEventLevel } from './types';

/** Define a stable platform event code. */
function code(
  category: string,
  name: string,
  level: PlatformEventLevel,
  message: string
): PlatformCodeDefinition {
  return {
    category,
    code: `${category}.${name}`,
    prefix: `ZERO_${category}_${name}`.replace(/[^A-Za-z0-9]+/g, '_').toUpperCase(),
    level,
    message,
  };
}

/** Stable platform observability codes. */
export const OBS_CODES = {
  APP_CLIENT_BUNDLE_READY: code('app', 'client_bundle.ready', 'info', 'Client bundle is ready.'),
  APP_CLIENT_BUNDLE_FAILED: code('app', 'client_bundle.failed', 'warn', 'Client bundle build failed; SSR-only mode is active.'),
  APP_STYLES_READY: code('app', 'styles.ready', 'info', 'Platform stylesheet is ready.'),
  APP_STYLES_FAILED: code('app', 'styles.failed', 'warn', 'Platform stylesheet build failed; pages may render unstyled.'),
  APP_LISTENING: code('app', 'listening', 'info', 'Application server is listening.'),
  APP_SHUTDOWN_SIGNAL: code('app', 'shutdown.signal', 'info', 'Shutdown signal received.'),
  APP_REQUEST_FAILED: code('app', 'request.failed', 'error', 'Request failed.'),
  APP_REQUEST_SLOW: code('app', 'request.slow', 'warn', 'Request exceeded the configured slow threshold.'),
  APP_LIFECYCLE_FAILED: code('app', 'lifecycle.failed', 'error', 'Elysia lifecycle handler failed.'),
  APP_LIFECYCLE_SLOW: code('app', 'lifecycle.slow', 'warn', 'Elysia lifecycle handler exceeded the configured slow threshold.'),

  OBSERVABILITY_FRONTEND_INGESTED: code('observability', 'frontend.ingested', 'debug', 'Frontend observability event ingested.'),
  OBSERVABILITY_FRONTEND_REJECTED: code('observability', 'frontend.rejected', 'warn', 'Frontend observability event rejected.'),
  OBSERVABILITY_ACCESS_DENIED: code('observability', 'access.denied', 'warn', 'Observability endpoint access denied.'),

  SYNC_STARTED: code('sync', 'started', 'info', 'Sync engine started.'),
  SYNC_STOPPED: code('sync', 'stopped', 'info', 'Sync engine stopped.'),
  SYNC_AUTH_REQUIRED_DEFAULTED: code('sync', 'auth.required_defaulted', 'warn', 'Auth-enabled app defaulted WebSocket sync to authenticated-only.'),
  SYNC_CHANGE_LISTENER_FAILED: code('sync', 'change_listener.failed', 'error', 'ReactiveDB change listener failed.'),
  SYNC_MODE_AUTO_LAZY: code('sync', 'mode.auto_lazy', 'warn', 'Table auto-resolved to lazy sync.'),
  SYNC_MODE_FULL_OVER_LIMIT: code('sync', 'mode.full_over_limit', 'warn', 'Explicit full-sync table exceeds the auto-lazy row limit.'),
  SYNC_MODE_WARN_OVER_LIMIT: code('sync', 'mode.warn_over_limit', 'warn', 'Auto table exceeded the row limit but warning mode kept full sync.'),
  SYNC_POLICY_CALLBACK_FAILED: code('sync', 'policy.callback_failed', 'warn', 'Sync policy callback failed; request was denied.'),
  DATA_QUERY_FAILED: code('data', 'query.failed', 'error', 'Data query endpoint failed.'),

  KV_STARTED: code('kv', 'started', 'info', 'Platform KV/cache service started.'),
  KV_STOPPED: code('kv', 'stopped', 'info', 'Platform KV/cache service stopped.'),
  KV_START_FAILED: code('kv', 'start.failed', 'error', 'Platform KV/cache service failed to start.'),
  KV_STOP_FAILED: code('kv', 'stop.failed', 'error', 'Platform KV/cache service failed to stop cleanly.'),
  KV_FLUSH_FAILED: code('kv', 'flush.failed', 'error', 'Platform KV/cache journal flush failed.'),
  KV_CHECKPOINT_FAILED: code('kv', 'checkpoint.failed', 'error', 'Platform KV/cache checkpoint failed.'),
  KV_JOURNAL_TAIL_RECOVERED: code('kv', 'journal.tail_recovered', 'warn', 'Platform KV/cache removed an incomplete final journal record.'),
  KV_LEGACY_PERSISTENCE_MIGRATED: code('kv', 'persistence.legacy_migrated', 'warn', 'Platform KV/cache migrated legacy persistence records.'),
  KV_RECOVERY_RECORDS_SKIPPED: code('kv', 'recovery.records_skipped', 'warn', 'Platform KV/cache skipped persistence data under the configured recovery policy.'),

  AUTH_STARTED: code('auth', 'started', 'info', 'Auth plugin started.'),
  AUTH_STOPPED: code('auth', 'stopped', 'info', 'Auth plugin stopped.'),
  AUTH_REQUEST_VALIDATION_REJECTED: code('auth', 'request_validation.rejected', 'warn', 'Auth request validation failed.'),
  AUTH_FIRST_ADMIN_BOOTSTRAPPED: code('auth', 'first_admin.bootstrapped', 'info', 'First admin user bootstrapped.'),
  AUTH_REGISTRATION_DISABLED: code('auth', 'registration.disabled', 'warn', 'Registration request rejected by auth policy.'),
  AUTH_ADMIN_USER_CREATED: code('auth', 'admin.user_created', 'info', 'Admin created a user.'),
  AUTH_ADMIN_USER_UPDATED: code('auth', 'admin.user_updated', 'info', 'Admin updated a user.'),
  AUTH_ADMIN_USER_DELETED: code('auth', 'admin.user_deleted', 'warn', 'Admin deleted a user.'),
  AUTH_ADMIN_PASSWORD_RESET: code('auth', 'admin.password_reset', 'warn', 'Admin reset a user password.'),
  AUTH_ADMIN_PASSWORD_CHANGE_REQUIREMENT_CLEARED: code('auth', 'admin.password_change_requirement_cleared', 'warn', 'Admin cleared a user password-change requirement.'),
  AUTH_ADMIN_SETUP_EMAIL_SENT: code('auth', 'admin.setup_email_sent', 'info', 'Admin sent an account setup email.'),
  AUTH_ADMIN_PASSWORD_RESET_EMAIL_SENT: code('auth', 'admin.password_reset_email_sent', 'warn', 'Admin sent a password reset email.'),
  AUTH_ADMIN_USER_SETUP_DELIVERY_FAILED: code('auth', 'admin.user_setup_delivery_failed', 'error', 'Admin-created user setup delivery failed.'),
  AUTH_ADMIN_PASSWORD_RESET_DELIVERY_FAILED: code('auth', 'admin.password_reset_delivery_failed', 'error', 'Admin password reset delivery failed.'),
  AUTH_ADMIN_MFA_REQUIRED: code('auth', 'admin.mfa_required', 'warn', 'Admin required MFA for a user.'),
  AUTH_ADMIN_MFA_CLEARED: code('auth', 'admin.mfa_cleared', 'warn', 'Admin cleared a user MFA requirement.'),
  AUTH_ADMIN_MFA_RESET: code('auth', 'admin.mfa_reset', 'warn', 'Admin reset a user MFA methods.'),
  AUTH_ADMIN_EMAIL_VERIFICATION_SENT: code('auth', 'admin.email_verification_sent', 'info', 'Admin sent a user email verification link.'),
  AUTH_ADMIN_EMAIL_VERIFIED: code('auth', 'admin.email_verified', 'warn', 'Admin marked a user email verified.'),
  AUTH_USER_PROPERTY_REJECTED: code('auth', 'user_property.rejected', 'warn', 'User property mutation rejected.'),
  AUTH_ACTION_TOKEN_CREATED: code('auth', 'action_token.created', 'info', 'Auth action token created.'),
  AUTH_ACTION_TOKEN_CONSUMED: code('auth', 'action_token.consumed', 'info', 'Auth action token consumed.'),
  AUTH_ACTION_TOKEN_REJECTED: code('auth', 'action_token.rejected', 'warn', 'Auth action token rejected.'),
  AUTH_PASSWORD_RESET_REQUESTED: code('auth', 'password_reset.requested', 'info', 'Password reset requested.'),
  AUTH_PASSWORD_RESET_SUPPRESSED: code('auth', 'password_reset.suppressed', 'info', 'Password reset request suppressed.'),
  AUTH_PASSWORD_RESET_DELIVERY_FAILED: code('auth', 'password_reset.delivery_failed', 'error', 'Password reset email delivery failed.'),
  AUTH_PASSWORD_RESET_SENT: code('auth', 'password_reset.sent', 'info', 'Password reset email sent.'),
  AUTH_PASSWORD_RESET_COMPLETED: code('auth', 'password_reset.completed', 'info', 'Password reset completed.'),
  AUTH_EMAIL_VERIFICATION_REQUESTED: code('auth', 'email_verification.requested', 'info', 'Email verification requested.'),
  AUTH_EMAIL_VERIFICATION_SENT: code('auth', 'email_verification.sent', 'info', 'Email verification email sent.'),
  AUTH_EMAIL_VERIFICATION_DELIVERY_FAILED: code('auth', 'email_verification.delivery_failed', 'error', 'Email verification delivery failed.'),
  AUTH_EMAIL_VERIFIED: code('auth', 'email.verified', 'info', 'User email verified.'),
  AUTH_EMAIL_OUTBOX_ENQUEUED: code('auth', 'email_outbox.enqueued', 'debug', 'Auth email request entered the durable outbox.'),
  AUTH_EMAIL_OUTBOX_SUPPRESSED: code('auth', 'email_outbox.suppressed', 'info', 'Auth email request was privately suppressed.'),
  AUTH_EMAIL_OUTBOX_RETRY: code('auth', 'email_outbox.retry', 'warn', 'Auth email delivery was scheduled for retry.'),
  AUTH_EMAIL_OUTBOX_DEAD: code('auth', 'email_outbox.dead', 'error', 'Auth email delivery exhausted retries or was permanently rejected.'),
  AUTH_EMAIL_OUTBOX_RECOVERED: code('auth', 'email_outbox.recovered', 'warn', 'Expired auth email delivery leases were recovered.'),
  AUTH_EMAIL_OUTBOX_WORKER_FAILED: code('auth', 'email_outbox.worker_failed', 'error', 'Auth email outbox worker iteration failed.'),
  AUTH_MFA_EMAIL_DELIVERY_FAILED: code('auth', 'mfa_email.delivery_failed', 'error', 'MFA email delivery failed.'),
  AUTH_ACCOUNT_SUSPENDED: code('auth', 'account.suspended', 'warn', 'Auth account suspended.'),
  AUTH_ACCOUNT_REACTIVATED: code('auth', 'account.reactivated', 'info', 'Auth account reactivated.'),
  AUTH_NATIVE_AUTHORIZATION_REQUESTED: code('auth', 'native.authorization_requested', 'info', 'Native app authorization requested.'),
  AUTH_NATIVE_AUTHORIZATION_APPROVED: code('auth', 'native.authorization_approved', 'info', 'Native app authorization approved.'),
  AUTH_NATIVE_AUTHORIZATION_DENIED: code('auth', 'native.authorization_denied', 'info', 'Native app authorization denied.'),
  AUTH_NATIVE_CODE_EXCHANGED: code('auth', 'native.code_exchanged', 'info', 'Native authorization code exchanged.'),
  AUTH_NATIVE_REFRESH_ROTATED: code('auth', 'native.refresh_rotated', 'debug', 'Native refresh token rotated.'),
  AUTH_NATIVE_REFRESH_REUSE: code('auth', 'native.refresh_reuse', 'warn', 'Native refresh token reuse revoked its session family.'),
  AUTH_NATIVE_SESSION_REVOKED: code('auth', 'native.session_revoked', 'info', 'Native app session revoked.'),

  TOKENS_STARTED: code('tokens', 'started', 'info', 'Platform token service started.'),
  TOKENS_STOPPED: code('tokens', 'stopped', 'info', 'Platform token service stopped.'),
  TOKENS_ACTION_CREATED: code('tokens', 'action.created', 'info', 'Platform action token created.'),
  TOKENS_ACTION_CONSUMED: code('tokens', 'action.consumed', 'info', 'Platform action token consumed.'),
  TOKENS_ACTION_REJECTED: code('tokens', 'action.rejected', 'warn', 'Platform action token rejected.'),
  TOKENS_RESUME_CREATED: code('tokens', 'resume.created', 'info', 'Platform resume token created.'),
  TOKENS_RESUME_VERIFIED: code('tokens', 'resume.verified', 'debug', 'Platform resume token verified.'),
  TOKENS_RESUME_ROTATED: code('tokens', 'resume.rotated', 'info', 'Platform resume token rotated.'),
  TOKENS_RESUME_REVOKED: code('tokens', 'resume.revoked', 'warn', 'Platform resume token revoked.'),
  TOKENS_RESUME_REJECTED: code('tokens', 'resume.rejected', 'warn', 'Platform resume token rejected.'),

  EMAIL_CONFIGURED: code('email', 'configured', 'info', 'Email runtime configured.'),
  EMAIL_SEND_REQUESTED: code('email', 'send.requested', 'info', 'Email send requested.'),
  EMAIL_SENT: code('email', 'sent', 'info', 'Email sent.'),
  EMAIL_SEND_FAILED: code('email', 'send.failed', 'error', 'Email send failed.'),
  EMAIL_CONSOLE_PREVIEW: code('email', 'console.preview', 'info', 'Console email provider captured a preview.'),

  AI_CONFIGURED: code('ai', 'configured', 'info', 'AI runtime configured.'),
  AI_PROVIDER_ENABLED: code('ai', 'provider.enabled', 'info', 'AI provider enabled.'),
  AI_PROVIDER_SKIPPED: code('ai', 'provider.skipped', 'warn', 'AI provider skipped.'),
  AI_PROVIDER_FAILED: code('ai', 'provider.failed', 'error', 'AI provider setup failed.'),
  AI_MODEL_ALIAS_UNRESOLVED: code('ai', 'model_alias.unresolved', 'warn', 'AI model alias is unresolved.'),
  AI_REQUEST_STARTED: code('ai', 'request.started', 'debug', 'AI request started.'),
  AI_REQUEST_COMPLETED: code('ai', 'request.completed', 'info', 'AI request completed.'),
  AI_REQUEST_FAILED: code('ai', 'request.failed', 'error', 'AI request failed.'),
  AI_TOOL_FAILED: code('ai', 'tool.failed', 'error', 'AI tool execution failed.'),
  AI_STATUS_ACCESS_DENIED: code('ai', 'status.access_denied', 'warn', 'AI status endpoint access denied.'),

  VECTOR_CONFIGURED: code('vector', 'configured', 'info', 'Vector runtime configured.'),
  VECTOR_INDEX_READY: code('vector', 'index.ready', 'info', 'Vector index ready.'),
  VECTOR_INDEX_FAILED: code('vector', 'index.failed', 'error', 'Vector index failed to initialize.'),
  VECTOR_OPERATION_COMPLETED: code('vector', 'operation.completed', 'debug', 'Vector operation completed.'),
  VECTOR_OPERATION_FAILED: code('vector', 'operation.failed', 'error', 'Vector operation failed.'),

  PDF_CONFIGURED: code('pdf', 'configured', 'info', 'PDF runtime configured.'),
  PDF_RENDER_STARTED: code('pdf', 'render.started', 'debug', 'PDF render started.'),
  PDF_RENDER_COMPLETED: code('pdf', 'render.completed', 'info', 'PDF render completed.'),
  PDF_RENDER_FAILED: code('pdf', 'render.failed', 'error', 'PDF render failed.'),
  PDF_STORED: code('pdf', 'stored', 'info', 'Generated PDF stored.'),
  PDF_STORAGE_FAILED: code('pdf', 'storage.failed', 'error', 'Generated PDF storage failed.'),
  PDF_STOPPED: code('pdf', 'stopped', 'info', 'PDF runtime stopped.'),

  RESOURCE_POLICY_EVALUATION_FAILED: code('resource', 'policy.evaluation_failed', 'warn', 'Resource policy evaluation failed; request was denied.'),
  RESOURCE_REGISTRY_READY: code('resource', 'registry.ready', 'info', 'Resource registry is ready.'),
  RESOURCE_LOAD_FAILED: code('resource', 'load.failed', 'error', 'App-owned resource module failed to load.'),
  RESOURCE_CRUD_FAILED: code('resource', 'crud.failed', 'error', 'Generated resource CRUD operation failed.'),

  STORAGE_STARTED: code('storage', 'started', 'info', 'Storage plugin started.'),
  STORAGE_STOPPED: code('storage', 'stopped', 'info', 'Storage plugin stopped.'),

  PERSISTENCE_SQL_OPENED: code('persistence', 'sql.opened', 'info', 'SQLite persistence service opened.'),
  PERSISTENCE_SQL_CLOSED: code('persistence', 'sql.closed', 'info', 'SQLite persistence service closed.'),
  PERSISTENCE_SQL_SNAPSHOT_WRITTEN: code('persistence', 'sql_snapshot.written', 'debug', 'SQLite hot snapshot written.'),
  PERSISTENCE_SQL_SNAPSHOT_FAILED: code('persistence', 'sql_snapshot.failed', 'error', 'SQLite hot snapshot failed.'),
  PERSISTENCE_SQL_CHECKPOINT_COMPLETED: code('persistence', 'sql_checkpoint.completed', 'debug', 'SQLite WAL checkpoint completed.'),
  PERSISTENCE_SQL_CHECKPOINT_FAILED: code('persistence', 'sql_checkpoint.failed', 'error', 'SQLite WAL checkpoint failed.'),

  NOTIFICATIONS_STARTED: code('notifications', 'started', 'info', 'Notifications plugin started.'),
  NOTIFICATIONS_STOPPED: code('notifications', 'stopped', 'info', 'Notifications plugin stopped.'),
  NOTIFICATIONS_CLEANUP: code('notifications', 'cleanup.expired', 'info', 'Expired notifications were cleaned up.'),

  ROOMS_STARTED: code('rooms', 'started', 'info', 'Rooms plugin started.'),
  ROOMS_STOPPED: code('rooms', 'stopped', 'info', 'Rooms plugin stopped.'),

  SCHEDULER_STARTED: code('scheduler', 'started', 'info', 'Scheduler started.'),
  SCHEDULER_STOPPED: code('scheduler', 'stopped', 'info', 'Scheduler stopped.'),
  SCHEDULER_ALL_STOPPED: code('scheduler', 'all_stopped', 'info', 'All scheduler jobs stopped.'),
  SCHEDULER_JOB_REGISTERED: code('scheduler', 'job.registered', 'info', 'Scheduler job registered.'),
  SCHEDULER_JOB_UNREGISTERED: code('scheduler', 'job.unregistered', 'info', 'Scheduler job unregistered.'),
  SCHEDULER_JOB_FAILED: code('scheduler', 'job.failed', 'error', 'Scheduler job failed.'),
  SCHEDULER_JOB_UNHANDLED_FAILED: code('scheduler', 'job.unhandled_failed', 'error', 'Scheduler job threw an unhandled error.'),

  WORKFLOWS_INITIALIZED: code('workflows', 'initialized', 'info', 'Workflow plugin initialized.'),
  WORKFLOWS_STOPPED: code('workflows', 'stopped', 'info', 'Workflow plugin stopped.'),
  WORKFLOWS_STARTUP_FAILED: code('workflows', 'startup.failed', 'error', 'Workflow plugin failed to initialize.'),
  WORKFLOWS_RECOVERED: code('workflows', 'recovered', 'info', 'In-flight workflow steps recovered.'),
  WORKFLOWS_RECOVERY_FAILED: code('workflows', 'recovery.failed', 'error', 'Workflow recovery failed.'),
  WORKFLOWS_PUBLICATION_FAILED: code('workflows', 'publication.failed', 'error', 'Workflow service publication failed.'),
  WORKFLOWS_SHUTDOWN_GRACE_EXHAUSTED: code('workflows', 'shutdown.grace_exhausted', 'warn', 'Workflow shutdown grace expired with handlers still running.'),
  WORKFLOW_DEFINITION_PUBLISHED: code('workflows', 'definition.published', 'info', 'Workflow definition version published.'),
  WORKFLOW_DEFINITION_ACTIVATED: code('workflows', 'definition.activated', 'info', 'Workflow definition version activated.'),
  WORKFLOW_DEFINITION_RETIRED: code('workflows', 'definition.retired', 'info', 'Workflow definition version retired.'),
  WORKFLOW_INSTANCE_STARTED: code('workflows', 'instance.started', 'info', 'Workflow instance started.'),
  WORKFLOW_INSTANCE_COMPLETED: code('workflows', 'instance.completed', 'info', 'Workflow instance completed.'),
  WORKFLOW_INSTANCE_FAILED: code('workflows', 'instance.failed', 'error', 'Workflow instance failed.'),
  WORKFLOW_INSTANCE_PAUSED: code('workflows', 'instance.paused', 'info', 'Workflow instance paused.'),
  WORKFLOW_INSTANCE_RESUMED: code('workflows', 'instance.resumed', 'info', 'Workflow instance resumed.'),
  WORKFLOW_INSTANCE_CANCELLED: code('workflows', 'instance.cancelled', 'info', 'Workflow instance cancelled.'),
  WORKFLOW_STEP_RETRY_SCHEDULED: code('workflows', 'step.retry_scheduled', 'warn', 'Workflow step retry scheduled.'),
  WORKFLOW_STEP_TIMED_OUT: code('workflows', 'step.timed_out', 'error', 'Workflow step timed out.'),
  WORKFLOW_HANDLER_MISSING: code('workflows', 'handler.missing', 'error', 'Workflow step handler is not registered.'),
  WORKFLOW_ADVANCE_FAILED: code('workflows', 'advance.failed', 'error', 'Workflow frontier advancement failed.'),
  WORKFLOW_NODE_COMPLETED: code('workflows', 'node.completed', 'debug', 'Workflow graph node completed.'),
  WORKFLOW_CHOICE_SELECTED: code('workflows', 'choice.selected', 'debug', 'Workflow choice branch selected.'),
  WORKFLOW_PARALLEL_STARTED: code('workflows', 'parallel.started', 'debug', 'Workflow parallel branches started.'),
  WORKFLOW_PARALLEL_JOINED: code('workflows', 'parallel.joined', 'debug', 'Workflow parallel branches joined.'),
  WORKFLOW_EACH_EXPANDED: code('workflows', 'each.expanded', 'debug', 'Workflow each items were durably expanded.'),
  WORKFLOW_EACH_COMPLETED: code('workflows', 'each.completed', 'debug', 'Workflow each fan-out completed.'),
  WORKFLOW_EACH_FAILED: code('workflows', 'each.failed', 'error', 'Workflow each fan-out failed.'),
  WORKFLOW_EACH_ITEM_FAILED: code('workflows', 'each.item_failed', 'error', 'Workflow each item failed.'),
  WORKFLOW_FANOUT_LIMIT_EXCEEDED: code('workflows', 'fanout.limit_exceeded', 'warn', 'Workflow fan-out exceeded its configured limit.'),
  WORKFLOW_MEMORY_LIMIT_REJECTED: code('workflows', 'memory.limit_rejected', 'warn', 'Workflow memory mutation exceeded a configured limit.'),
  WORKFLOW_MEMORY_CONFLICT: code('workflows', 'memory.conflict', 'warn', 'Workflow memory mutation conflicted with durable state.'),
  WORKFLOW_INTERACTION_OPENED: code('workflows', 'interaction.opened', 'info', 'Workflow interaction opened.'),
  WORKFLOW_INTERACTION_SUBMISSION_REJECTED: code('workflows', 'interaction.submission_rejected', 'warn', 'Workflow interaction submission was rejected.'),
  WORKFLOW_INTERACTION_ACCEPTED: code('workflows', 'interaction.accepted', 'info', 'Workflow interaction submission was accepted.'),
  WORKFLOW_INTERACTION_EXPIRED: code('workflows', 'interaction.expired', 'info', 'Workflow interaction expired.'),
  WORKFLOW_INTERACTION_DELIVERY_FAILED: code('workflows', 'interaction.delivery_failed', 'error', 'Workflow interaction delivery failed.'),

  ROUTER_LAYOUT_CONFIG_FAILED: code('router', 'layout_config.failed', 'warn', 'Router layout config import failed.'),
  ROUTER_SERVER_ROUTES_LOADED: code('router', 'server_routes.loaded', 'info', 'App-owned Elysia server routes loaded.'),
  ROUTER_SERVER_ROUTE_LOAD_FAILED: code('router', 'server_route.load_failed', 'error', 'App-owned Elysia server route failed to load.'),
  ROUTER_MIDDLEWARE_MATCHER_INVALID: code('router', 'middleware.matcher_invalid', 'warn', 'App-owned middleware matcher is invalid.'),
  ROUTER_MIDDLEWARE_POLICY_AUTH_UNAVAILABLE: code('router', 'middleware_policy.auth_unavailable', 'warn', 'App-owned middleware policy requires auth services that are unavailable.'),
  RENDERER_PAGE_EXPORT_MISSING: code('renderer', 'page_export.missing', 'error', 'Page module has no default export.'),
  RENDERER_SSR_ERROR: code('renderer', 'ssr.error', 'error', 'Streaming SSR reported an error.'),
  RENDERER_FATAL_ERROR: code('renderer', 'fatal.error', 'error', 'Route rendering failed.'),

  FRONTEND_RENDER_ERROR: code('frontend', 'render.error', 'error', 'Frontend render error caught by ErrorBoundary.'),
  FRONTEND_HYDRATE_FAILED: code('frontend', 'hydrate.failed', 'error', 'Hydration failed.'),
  FRONTEND_HYDRATE_MISSING_ROOT: code('frontend', 'hydrate.missing_root', 'error', 'Hydration root element is missing.'),
  FRONTEND_HYDRATE_MISSING_ROUTE_DATA: code('frontend', 'hydrate.missing_route_data', 'error', 'Hydration route data is missing.'),
  FRONTEND_HYDRATE_MISSING_MANIFEST_ENTRY: code('frontend', 'hydrate.missing_manifest_entry', 'error', 'Hydration manifest entry is missing.'),
  FRONTEND_HYDRATE_MISSING_PAGE_EXPORT: code('frontend', 'hydrate.missing_page_export', 'error', 'Hydration page module has no default export.'),
  FRONTEND_NOTIFICATION_RECEIPT_FAILED: code('frontend', 'notification.receipt_failed', 'error', 'Notification receipt action failed.'),
  FRONTEND_AUTH_ACTION_FAILED: code('frontend', 'auth.action_failed', 'error', 'Frontend auth action failed.'),
  FRONTEND_AUTH_SESSION_REDIRECT: code('frontend', 'auth.session_redirect', 'warn', 'Frontend redirected after auth session ended.'),
  FRONTEND_ADMIN_USER_ACTION_FAILED: code('frontend', 'admin_user.action_failed', 'error', 'Admin user-management action failed.'),
  FRONTEND_STORAGE_ACTION_FAILED: code('frontend', 'storage.action_failed', 'error', 'Storage management action failed.'),
  FRONTEND_DATA_PAGE_FAILED: code('frontend', 'data_page.failed', 'error', 'Frontend data page query failed.'),
  FRONTEND_RESOURCE_ACTION_FAILED: code('frontend', 'resource.action_failed', 'error', 'Frontend generated-resource action failed.'),
  FRONTEND_MUTATION_FAILED: code('frontend', 'mutation.failed', 'error', 'Frontend mutation action failed.'),
  FRONTEND_COPY_FAILED: code('frontend', 'copy.failed', 'error', 'Clipboard copy action failed.'),
  FRONTEND_CODE_HIGHLIGHT_FAILED: code('frontend', 'code_highlight.failed', 'warn', 'Frontend code block highlighting failed.'),

  MIGRATOR_LOG: code('migrations', 'log', 'info', 'Migration runner emitted a log message.'),
  MIGRATOR_FAILED: code('migrations', 'failed', 'error', 'Migration failed.'),
} as const;

export type ObservabilityCodeName = keyof typeof OBS_CODES;
