/**
 * migration-planner.ts
 *
 * Turns schema diff findings into reviewable draft SQL. It never applies SQL;
 * the generated plan is meant for migration files and human review.
 */

import type { TableSchema } from '../sync/types';
import { isIsolatedDatabaseColumnDefinition } from '../sync/row-identity';
import { classifyAddColumnDefinition } from './add-column-classifier';
import { diffSchemaSnapshots } from './schema-diff';
import {
  snapshotDeclaredTables,
  stableStringify,
} from './schema-snapshot';
import type {
  MigrationPlan,
  MigrationPlanStatement,
  MigrationSafety,
  SchemaDiffIssue,
  SchemaSnapshot,
} from './types';

/** Build a migration plan from declared tables and an inspected DB snapshot. */
export function createMigrationPlan(
  declaredTables: Record<string, TableSchema>,
  actual: SchemaSnapshot,
): MigrationPlan {
  assertPlanColumnDefinitions(declaredTables);
  const declared = snapshotDeclaredTables(declaredTables);
  const issues = diffSchemaSnapshots(declared, actual);
  const statements = createStatements(declaredTables, issues);
  const safety = maxSafety([
    ...issues.map((issue) => issue.safety),
    ...statements.map((statement) => statement.safety),
  ]);

  return {
    issues,
    statements,
    safety,
    needsManualReview: safety !== 'safe' || issues.some((issue) => issue.safety === 'manual'),
  };
}

/** Render a plan as a draft migration file body. */
export function renderMigrationPlan(params: {
  version: string;
  description: string;
  plan: MigrationPlan;
}): string {
  const statements = params.plan.statements
    .map((statement) => `    db.run(${JSON.stringify(statement.sql)});`)
    .join('\n');
  const issueComment = params.plan.issues
    .map((issue) => ` * - [${issue.severity}] ${issue.message}`)
    .join('\n');

  return `/**
 * ${params.version}_${slugify(params.description)}.ts
 *
 * Draft migration generated by migrate:plan.
 *
${issueComment || ' * No schema drift issues were detected.'}
 */

import type { Database } from 'bun:sqlite';
import type { Migration } from '../migrator';

export const migration: Migration = {
  version: '${params.version}',
  description: ${JSON.stringify(params.description)},
  safety: '${params.plan.safety}',

  up(db: Database) {
${statements || '    // No safe SQL statements were generated.'}
  },

  down(_db: Database) {
    // TODO: write rollback logic before relying on migrate:down for this migration.
  },
};
`;
}

function createStatements(
  declaredTables: Record<string, TableSchema>,
  issues: SchemaDiffIssue[],
): MigrationPlanStatement[] {
  const statements: MigrationPlanStatement[] = [];

  for (const issue of issues) {
    if (!issue.table) continue;
    const schema = declaredTables[issue.table];

    if (issue.kind === 'missing-table' && schema) {
      statements.push({
        sql: createTableSql(issue.table, schema),
        safety: 'safe',
        reason: issue.message,
      });
      for (const indexSql of createIdentityIndexSql(issue.table, schema)) {
        statements.push({
          sql: indexSql,
          safety: 'guarded',
          reason: `Create natural identity index for "${issue.table}".`,
        });
      }
    }

    if (issue.kind === 'missing-column' && schema && issue.column) {
      const definition = schema[issue.column];
      const addColumn = typeof definition === 'string'
        ? classifyAddColumnDefinition(definition)
        : null;
      if (typeof definition === 'string' && addColumn?.emit) {
        statements.push({
          sql: `ALTER TABLE ${quoteIdentifier(issue.table)} ADD COLUMN ${quoteIdentifier(issue.column)} ${definition}`,
          safety: addColumn.safety,
          reason: issue.message,
        });
      }
    }

    if (issue.kind === 'missing-identity-index' && schema) {
      for (const indexSql of createIdentityIndexSql(issue.table, schema)) {
        statements.push({
          sql: indexSql,
          safety: 'guarded',
          reason: issue.message,
        });
      }
    }
  }

  return dedupeStatements(statements);
}

function createTableSql(table: string, schema: TableSchema): string {
  const columns = Object.entries(schema)
    .filter(([key, value]) => key !== '_identity' && typeof value === 'string')
    .map(([column, definition]) => `${quoteIdentifier(column)} ${definition}`);
  return `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(table)} (${columns.join(', ')})`;
}

function createIdentityIndexSql(table: string, schema: TableSchema): string[] {
  if (!Array.isArray(schema._identity) || schema._identity.length === 0) return [];
  const indexName = `idx_${table}_identity`;
  const columns = schema._identity.map(quoteIdentifier).join(', ');
  return [
    `CREATE UNIQUE INDEX IF NOT EXISTS ${quoteIdentifier(indexName)} ON ${quoteIdentifier(table)} (${columns})`,
  ];
}

function assertPlanColumnDefinitions(
  declaredTables: Record<string, TableSchema>,
): void {
  for (const [table, schema] of Object.entries(declaredTables)) {
    for (const [column, definition] of Object.entries(schema)) {
      if (column === '_identity') continue;
      if (!isIsolatedDatabaseColumnDefinition(definition)) {
        throw new Error(
          `[migrator] Table "${table}" column "${column}" must describe exactly one isolated SQL column.`,
        );
      }
    }
  }
}

function dedupeStatements(statements: MigrationPlanStatement[]): MigrationPlanStatement[] {
  const seen = new Set<string>();
  return statements.filter((statement) => {
    const key = stableStringify(statement);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function maxSafety(values: MigrationSafety[]): MigrationSafety {
  const order: Record<MigrationSafety, number> = {
    safe: 0,
    guarded: 1,
    destructive: 2,
    manual: 3,
  };
  return values.reduce<MigrationSafety>((max, value) =>
    order[value] > order[max] ? value : max
  , 'safe');
}

function quoteIdentifier(identifier: string): string {
  return `"${identifier.replace(/"/g, '""')}"`;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 80) || 'migration';
}
