/** Refresh Zero's pinned official Public Suffix List asset. */

import { createHash } from 'node:crypto';
import { mkdir, rename, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const SOURCE = 'https://publicsuffix.org/list/public_suffix_list.dat';
const target = resolve(import.meta.dir, '../src/auth/vendor/public_suffix_list.txt');
const metadataTarget = resolve(
  import.meta.dir,
  '../src/auth/vendor/public-suffix-list-metadata.ts',
);

const response = await fetch(SOURCE, {
  redirect: 'error',
  signal: AbortSignal.timeout(30_000),
});
if (!response.ok) throw new Error(`PSL download failed with HTTP ${response.status}`);
const text = await response.text();
if (!text.startsWith('// This Source Code Form is subject to the terms of the Mozilla Public')
  || !text.includes('// ===BEGIN ICANN DOMAINS===')
  || !text.includes('// ===END ICANN DOMAINS===')
  || !text.includes('// ===BEGIN PRIVATE DOMAINS===')
  || !text.includes('// ===END PRIVATE DOMAINS===')) {
  throw new Error('Downloaded PSL is missing its license or ICANN/PRIVATE sections.');
}
const version = /^\/\/ VERSION: (.+)$/m.exec(text)?.[1];
const commit = /^\/\/ COMMIT: ([0-9a-f]{40})$/m.exec(text)?.[1];
if (!version || !commit) throw new Error('Downloaded PSL is missing version metadata.');
const sha256 = createHash('sha256').update(text).digest('hex');
const metadata = `/** Generated by scripts/update-public-suffix-list.ts. */
export const PUBLIC_SUFFIX_LIST_METADATA = Object.freeze({
  source: ${JSON.stringify(SOURCE)},
  version: ${JSON.stringify(version)},
  commit: ${JSON.stringify(commit)},
  sha256: ${JSON.stringify(sha256)},
  license: 'MPL-2.0',
  includes: Object.freeze(['ICANN', 'PRIVATE'] as const),
});
`;

await mkdir(dirname(target), { recursive: true });
const nonce = crypto.randomUUID();
const textTemp = `${target}.${nonce}.tmp`;
const metadataTemp = `${metadataTarget}.${nonce}.tmp`;
await writeFile(textTemp, text, { encoding: 'utf8', mode: 0o644 });
await writeFile(metadataTemp, metadata, { encoding: 'utf8', mode: 0o644 });
await rename(textTemp, target);
await rename(metadataTemp, metadataTarget);
console.log(`Updated PSL ${version} (${sha256}) from ${SOURCE}`);
