/** Public contracts and stable framework-owned errors for table mutations. */

export type DataTableMutationKind = 'row' | 'bulk' | 'cell';
export type DataTableMutationFailureStage = 'execute' | 'refresh';

export interface DataTableMutationContext {
  /** Aborted when the table's authorization/data boundary changes or unmounts. */
  readonly signal: AbortSignal;
  /** Opaque identifier for correlating work within the caller's own process. */
  readonly operationId: string;
}

export interface DataTableMutationOperation<Result = void> {
  /** Opaque, component-local deduplication key. It is never emitted. */
  readonly key: string;
  readonly kind: DataTableMutationKind;
  readonly execute: (
    context: DataTableMutationContext,
  ) => Result | Promise<Result>;
  /** Refresh after success. Defaults to true when a refresh callback exists. */
  readonly refreshOnSuccess?: boolean;
  /** Per-operation refresh override. */
  readonly refresh?: () => void | Promise<void>;
}

export interface DataTableMutationFailure {
  readonly code: 'DATA_TABLE_MUTATION_FAILED';
  /** Safe, framework-owned text suitable for inline UI. */
  readonly message: string;
  readonly kind: DataTableMutationKind;
  /** A refresh failure never makes retry repeat an accepted write. */
  readonly stage: DataTableMutationFailureStage;
}

export type DataTableMutationLifecycleErrorCode =
  | 'DATA_TABLE_MUTATION_SCOPE_UNAVAILABLE'
  | 'DATA_TABLE_MUTATION_CANCELLED'
  | 'DATA_TABLE_MUTATION_RETRY_UNAVAILABLE'
  | 'DATA_TABLE_MUTATION_ACTION_UNAVAILABLE';

/** Stable errors generated by the table lifecycle itself, never by app code. */
export class DataTableMutationLifecycleError extends Error {
  readonly code: DataTableMutationLifecycleErrorCode;

  constructor(code: DataTableMutationLifecycleErrorCode, message: string) {
    super(message);
    this.name = 'DataTableMutationLifecycleError';
    this.code = code;
  }
}

export interface DataTableMutationControllerOptions {
  boundaryKey: string;
  available?: boolean;
  refresh?: () => void | Promise<void>;
  failureMessage?: (
    kind: DataTableMutationKind,
    stage: DataTableMutationFailureStage,
  ) => string;
  onFailure?: (failure: DataTableMutationFailure) => void;
}

export function mutationCancelledError(): DataTableMutationLifecycleError {
  return new DataTableMutationLifecycleError(
    'DATA_TABLE_MUTATION_CANCELLED',
    'The table operation was cancelled before it completed.',
  );
}

export function isDataTableMutationCancellation(
  value: unknown,
): value is DataTableMutationLifecycleError {
  return value instanceof DataTableMutationLifecycleError
    && value.code === 'DATA_TABLE_MUTATION_CANCELLED';
}

export function dataTableMutationScopeUnavailableError(): DataTableMutationLifecycleError {
  return new DataTableMutationLifecycleError(
    'DATA_TABLE_MUTATION_SCOPE_UNAVAILABLE',
    'Table actions are unavailable during an authorization scope transition.',
  );
}

export function dataTableMutationActionUnavailableError(
  action: 'insert' | 'update' | 'remove',
): DataTableMutationLifecycleError {
  return new DataTableMutationLifecycleError(
    'DATA_TABLE_MUTATION_ACTION_UNAVAILABLE',
    `This table source does not provide a ${action} operation.`,
  );
}

export function dataTableMutationFailureMessage(
  kind: DataTableMutationKind,
  stage: DataTableMutationFailureStage = 'execute',
): string {
  if (stage === 'refresh') {
    return kind === 'cell'
      ? 'The change was saved, but the table could not refresh. Retry refresh.'
      : 'The action completed, but the table could not refresh. Retry refresh.';
  }
  if (kind === 'cell') return 'The change could not be saved. Try again.';
  if (kind === 'bulk') return 'The bulk action could not be completed. Try again.';
  return 'The row action could not be completed. Try again.';
}
