/**
 * Callback-free, structured-clone-safe contracts for asynchronous Zero
 * database executors. Actor routing, physical paths, raw SQL, and
 * authorization-derived database selection deliberately live elsewhere.
 */

import { REACTIVE_DB_ROW_ID_MAX_BYTES } from '../sync/row-identity';

/** Maximum nesting accepted in an operation payload. */
export const DATABASE_OPERATION_MAX_DEPTH = 16;

/** Maximum total scalar/container nodes accepted in one operation. */
export const DATABASE_OPERATION_MAX_NODES = 10_000;

/** Maximum estimated UTF-8 payload size accepted in one operation. */
export const DATABASE_OPERATION_MAX_BYTES = 1_048_576;

/** Maximum UTF-8 size of one string value. */
export const DATABASE_OPERATION_MAX_STRING_BYTES = 262_144;

/** Maximum number of properties in one payload object. */
export const DATABASE_OPERATION_MAX_OBJECT_ENTRIES = 1_024;

/** Maximum number of items in one payload array. */
export const DATABASE_OPERATION_MAX_ARRAY_ITEMS = 10_000;

/** Maximum number of mutations or assertions in one atomic batch. */
export const DATABASE_OPERATION_MAX_BATCH_ITEMS = 256;

/** Maximum rows one built-in list operation may request. */
export const DATABASE_LIST_MAX_ROWS = 500;

/**
 * Maximum rows one structured find operation may request. The extra row
 * preserves Zero Resource's bounded 1000-row page plus has-more lookahead.
 */
export const DATABASE_FIND_MAX_ROWS = 1_001;

/** Maximum offset accepted by one structured find operation. */
export const DATABASE_FIND_MAX_OFFSET = 1_000_000;

/** Maximum explicitly projected columns in one structured find. */
export const DATABASE_FIND_MAX_PROJECTION_FIELDS = 128;

/** Maximum ordered fields before the actor adds its primary-key tie-breaker. */
export const DATABASE_FIND_MAX_ORDER_FIELDS = 8;

/** Maximum total filter nodes accepted by one structured find. */
export const DATABASE_FIND_MAX_FILTERS = 64;

/** Maximum nesting of allOf/anyOf groups in one structured find. */
export const DATABASE_FIND_MAX_FILTER_DEPTH = 8;

/** Maximum scalar values accepted by one structured `in` filter. */
export const DATABASE_FIND_MAX_IN_VALUES = 50;

/** Maximum SQLite bind parameters generated by one structured find. */
export const DATABASE_FIND_MAX_PARAMETERS = 256;

/** Maximum UTF-8 size of a row primary-key value. */
export const DATABASE_OPERATION_MAX_ID_BYTES = REACTIVE_DB_ROW_ID_MAX_BYTES;

/** Maximum length of a registry/table name. */
export const DATABASE_OPERATION_MAX_NAME_LENGTH = 128;

/** Maximum length of a write idempotency key. */
export const DATABASE_IDEMPOTENCY_KEY_MAX_LENGTH = 128;

/** JSON-compatible scalar supported by the executor protocol. */
export type DatabaseSerializableScalar = string | number | boolean | null;

/**
 * Canonical payload supported by database operations and actor-local handlers.
 *
 * It is intentionally narrower than JavaScript structured clone: values which
 * are lossy in ReactiveDB's durable change/receipt representation (undefined,
 * bigint, Date, Map, Set, typed arrays, custom prototypes, and sparse arrays)
 * are rejected before dispatch.
 */
export type DatabaseSerializableValue =
  | DatabaseSerializableScalar
  | readonly DatabaseSerializableValue[]
  | { readonly [key: string]: DatabaseSerializableValue };

/** Canonical row/patch data accepted by managed ReactiveDB mutations. */
export type DatabaseOperationRow = Readonly<
  Record<string, DatabaseSerializableValue>
>;

/** Durable per-database ordering token returned by every successful operation. */
export interface DatabaseSequenceToken {
  readonly seq: number;
}

export interface DatabaseSnapshotConsistency {
  readonly mode: 'snapshot';
}

export interface DatabaseReadYourWritesConsistency {
  readonly mode: 'read-your-writes';
  readonly minSeq: DatabaseSequenceToken;
}

export interface DatabaseStrongConsistency {
  readonly mode: 'strong';
}

/** Explicit read routing and visibility guarantee. */
export type DatabaseReadConsistency =
  | DatabaseSnapshotConsistency
  | DatabaseReadYourWritesConsistency
  | DatabaseStrongConsistency;

/** Built-in primary-key lookup. */
export interface DatabaseGetOperation {
  readonly type: 'get';
  readonly table: string;
  readonly id: string;
  readonly consistency?: DatabaseReadConsistency;
}

/**
 * Built-in bounded primary-key page.
 *
 * Actors order by the declared primary key ascending and apply `after` as an
 * exclusive cursor. `limit` is required so no valid operation means "scan the
 * complete table".
 */
export interface DatabaseListOperation {
  readonly type: 'list';
  readonly table: string;
  readonly limit: number;
  readonly after?: string;
  readonly consistency?: DatabaseReadConsistency;
}

/** Comparison operators supported by the schema-validated find contract. */
export type DatabaseFindFilterOperator =
  | 'eq'
  | 'ne'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'like'
  | 'contains'
  | 'in';

/** One schema-validated field predicate. */
export interface DatabaseFindFieldFilter {
  readonly type: 'field';
  readonly field: string;
  readonly operator: DatabaseFindFilterOperator;
  readonly value: DatabaseSerializableScalar | readonly DatabaseSerializableScalar[];
  /**
   * Framework-owned equality constraints may require storage-class and BINARY
   * equality so SQLite affinity/collation cannot broaden an authorization
   * predicate. It is intentionally valid only for eq/ne.
   */
  readonly match?: 'exact';
}

/** A non-empty nested conjunction or disjunction of find predicates. */
export interface DatabaseFindFilterGroup {
  readonly type: 'allOf' | 'anyOf';
  readonly filters: readonly DatabaseFindFilter[];
}

/** Recursive, declarative find predicate with no raw SQL escape hatch. */
export type DatabaseFindFilter =
  | DatabaseFindFieldFilter
  | DatabaseFindFilterGroup;

/** One deterministic structured-find ordering term. */
export interface DatabaseFindOrder {
  readonly field: string;
  readonly direction: 'asc' | 'desc';
}

/** Built-in bounded, schema-validated filtered read. */
export interface DatabaseFindOperation {
  readonly type: 'find';
  readonly table: string;
  readonly select?: readonly string[];
  /** Top-level predicates are joined with AND. */
  readonly filters?: readonly DatabaseFindFilter[];
  readonly order?: readonly DatabaseFindOrder[];
  readonly limit: number;
  readonly offset?: number;
  readonly consistency?: DatabaseReadConsistency;
}

/** Invoke a named, actor-local, synchronous read handler. */
export interface DatabaseQueryOperation {
  readonly type: 'query';
  readonly name: string;
  readonly input: DatabaseSerializableValue;
  readonly consistency?: DatabaseReadConsistency;
}

/** Strict insert. The actor maps this to ReactiveDB.createStrict(). */
export interface DatabaseCreateMutation {
  readonly type: 'create';
  readonly table: string;
  readonly row: DatabaseOperationRow;
}

/** Primary-key upsert. The actor maps this to ReactiveDB.create()/insert(). */
export interface DatabaseUpsertMutation {
  readonly type: 'upsert';
  readonly table: string;
  readonly row: DatabaseOperationRow;
}

/** Partial primary-key update. */
export interface DatabaseUpdateMutation {
  readonly type: 'update';
  readonly table: string;
  readonly id: string;
  readonly patch: DatabaseOperationRow;
}

/** Primary-key delete. */
export interface DatabaseDeleteMutation {
  readonly type: 'delete';
  readonly table: string;
  readonly id: string;
}

/** Safe CRUD primitives executable by the writer actor. */
export type DatabaseMutation =
  | DatabaseCreateMutation
  | DatabaseUpsertMutation
  | DatabaseUpdateMutation
  | DatabaseDeleteMutation;

/** Require that a primary-key row exists at the batch snapshot. */
export interface DatabaseRowExistsAssertion {
  readonly type: 'row-exists';
  readonly table: string;
  readonly id: string;
}

/** Require that a primary-key row is absent at the batch snapshot. */
export interface DatabaseRowMissingAssertion {
  readonly type: 'row-missing';
  readonly table: string;
  readonly id: string;
}

/** Require exact canonical equality with the current primary-key row. */
export interface DatabaseRowEqualsAssertion {
  readonly type: 'row-equals';
  readonly table: string;
  readonly id: string;
  readonly row: DatabaseOperationRow;
}

/** Require the durable database sequence to equal a known token. */
export interface DatabaseSequenceEqualsAssertion {
  readonly type: 'sequence-equals';
  readonly sequence: DatabaseSequenceToken;
}

/** Declarative preconditions evaluated inside the batch transaction. */
export type DatabaseAssertion =
  | DatabaseRowExistsAssertion
  | DatabaseRowMissingAssertion
  | DatabaseRowEqualsAssertion
  | DatabaseSequenceEqualsAssertion;

/** Execute one managed mutation with a durable deduplication key. */
export interface DatabaseMutateOperation {
  readonly type: 'mutate';
  readonly idempotencyKey: string;
  readonly mutation: DatabaseMutation;
}

/** Evaluate assertions and mutations atomically in their declared order. */
export interface DatabaseBatchOperation {
  readonly type: 'batch';
  readonly idempotencyKey: string;
  readonly assertions?: readonly DatabaseAssertion[];
  readonly mutations: readonly DatabaseMutation[];
}

/** Invoke a named, actor-local, synchronous write handler exactly once. */
export interface DatabaseCommandOperation {
  readonly type: 'command';
  readonly name: string;
  readonly input: DatabaseSerializableValue;
  readonly idempotencyKey: string;
}

export type DatabaseReadOperation =
  | DatabaseGetOperation
  | DatabaseListOperation
  | DatabaseFindOperation
  | DatabaseQueryOperation;

export type DatabaseWriteOperation =
  | DatabaseMutateOperation
  | DatabaseBatchOperation
  | DatabaseCommandOperation;

/** Complete callback-free public operation union. */
export type DatabaseOperation = DatabaseReadOperation | DatabaseWriteOperation;

/** A read value and the durable sequence represented by its SQLite snapshot. */
export interface DatabaseReadResult<T extends DatabaseSerializableValue = DatabaseSerializableValue> {
  readonly value: T;
  readonly sequence: DatabaseSequenceToken;
}

/** A committed value and its durable sequence/idempotency receipt. */
export interface DatabaseCommitResult<T extends DatabaseSerializableValue = DatabaseSerializableValue> {
  readonly value: T;
  readonly sequence: DatabaseSequenceToken;
  readonly idempotencyKey: string;
  /** True when a prior durable receipt supplied the result without re-execution. */
  readonly replayed: boolean;
}

/** One bounded built-in list page and the exclusive cursor for the next page. */
export type DatabaseListPage = Readonly<{
  readonly rows: readonly DatabaseOperationRow[];
  readonly nextCursor: string | null;
}>;

/** Public convenience input for a bounded list page. */
export interface DatabaseListPageOptions {
  readonly limit: number;
  readonly after?: string;
}

/** Public convenience input for one structured find. */
export interface DatabaseFindInput {
  readonly select?: readonly string[];
  readonly filters?: readonly DatabaseFindFilter[];
  readonly order?: readonly DatabaseFindOrder[];
  readonly limit: number;
  readonly offset?: number;
}

/** Rows returned by one structured find operation. */
export type DatabaseFindRows = readonly DatabaseOperationRow[];

/** Low-level asynchronous executor contract used by bound public facades. */
export interface AsyncDatabaseOperationExecutor {
  execute(
    operation: DatabaseReadOperation,
    options?: DatabaseOperationExecutionOptions,
  ): Promise<DatabaseReadResult>;
  execute(
    operation: DatabaseWriteOperation,
    options?: DatabaseOperationExecutionOptions,
  ): Promise<DatabaseCommitResult>;
  execute(
    operation: DatabaseOperation,
    options?: DatabaseOperationExecutionOptions,
  ): Promise<DatabaseReadResult | DatabaseCommitResult>;
}

/** Cancellation and bounded-wait policy for one actor-backed operation. */
export interface DatabaseOperationExecutionOptions {
  /** Cancellation is honored only before actor dispatch. */
  readonly signal?: AbortSignal;
  /** Maximum time waiting for writer-lane admission. */
  readonly queueTimeoutMs?: number;
  /** Maximum time awaiting the dispatched actor result. */
  readonly operationTimeoutMs?: number;
}

/** Read consistency plus bounded-wait policy. */
export interface DatabaseReadOptions extends DatabaseOperationExecutionOptions {
  readonly consistency?: DatabaseReadConsistency;
}

/** Serializable idempotency and bounded-wait policy for a mutation/command. */
export interface DatabaseMutationOptions extends DatabaseOperationExecutionOptions {
  readonly idempotencyKey: string;
}

/** Serializable input for one atomic batch call. */
export interface DatabaseBatchInput {
  readonly assertions?: readonly DatabaseAssertion[];
  readonly mutations: readonly DatabaseMutation[];
}

/**
 * Intended bound application facade. Implementations derive database routing
 * from trusted context; no path, logical database id, or tenant id is accepted.
 */
export interface AsyncDatabaseClient {
  get(
    table: string,
    id: string,
    options?: DatabaseReadOptions,
  ): Promise<DatabaseReadResult<DatabaseOperationRow | null>>;
  list(
    table: string,
    page: DatabaseListPageOptions,
    options?: DatabaseReadOptions,
  ): Promise<DatabaseReadResult<DatabaseListPage>>;
  find(
    table: string,
    input: DatabaseFindInput,
    options?: DatabaseReadOptions,
  ): Promise<DatabaseReadResult<DatabaseFindRows>>;
  query(
    name: string,
    input: DatabaseSerializableValue,
    options?: DatabaseReadOptions,
  ): Promise<DatabaseReadResult<DatabaseSerializableValue>>;
  mutate(
    mutation: DatabaseMutation,
    options: DatabaseMutationOptions,
  ): Promise<DatabaseCommitResult>;
  batch(
    input: DatabaseBatchInput,
    options: DatabaseMutationOptions,
  ): Promise<DatabaseCommitResult>;
  command(
    name: string,
    input: DatabaseSerializableValue,
    options: DatabaseMutationOptions,
  ): Promise<DatabaseCommitResult<DatabaseSerializableValue>>;
}

/** Local registry knowledge used for admission before an actor executes work. */
export interface DatabaseOperationCatalog {
  readonly tables?: readonly string[];
  readonly queries?: readonly string[];
  readonly commands?: readonly string[];
  /** Optional actor-local column catalog for strict managed-mutation admission. */
  readonly columns?: Readonly<Record<string, readonly string[]>>;
  /** Optional actor-local primary-key catalog used to reject PK patches. */
  readonly primaryKeys?: Readonly<Record<string, string>>;
}
